"""MHR 18439-vertex mesh → 43-marker clinical atlas (LaiUhlrich2022 / SAM4Dcap).

41 surface markers (vertex lookup) + 2 computed hip joint centers (Bell's method).
Marker names use SAM4Dcap `*_study` convention for direct TRC↔OpenSim matching.

Generated by: scripts/build_mhr_atlas.py (symmetry enforcer)
Mapped: 41/41 surface markers.
Generated: 2026-02-26T12:58:47.205124+00:00
"""

from __future__ import annotations

import numpy as np

# Surface markers: SAM4Dcap study name → MHR vertex index
# 41 markers: 20 right + 20 left + 1 midline (C7)
MHR_SURFACE_MARKERS: dict[str, int] = {
    # ── Pelvis ──
    "r.ASIS_study": 7582,
    "L.ASIS_study": 6419,
    "r.PSIS_study": 7201,
    "L.PSIS_study": 6092,
    # ── Spine/Torso ──
    "C7_study": 5759,
    # ── Shoulders ──
    "r_shoulder_study": 8028,
    "L_shoulder_study": 6849,
    # ── Knees ──
    "r_knee_study": 16839,
    "r_mknee_study": 16727,
    "L_knee_study": 11642,
    "L_mknee_study": 11562,
    # ── Ankles ──
    "r_ankle_study": 17683,
    "r_mankle_study": 17408,
    "L_ankle_study": 12485,
    "L_mankle_study": 12235,
    # ── Feet ──
    "r_toe_study": 18415,
    "r_5meta_study": 18224,
    "r_calc_study": 17603,
    "L_toe_study": 13232,
    "L_5meta_study": 13035,
    "L_calc_study": 12467,
    # ── Elbows ──
    "r_lelbow_study": 13592,
    "r_melbow_study": 13445,
    "L_lelbow_study": 8436,
    "L_melbow_study": 8263,
    # ── Wrists ──
    "r_lwrist_study": 14294,
    "r_mwrist_study": 13911,
    "L_lwrist_study": 9113,
    "L_mwrist_study": 8742,
    # ── Thigh clusters ──
    "r_thigh1_study": 16414,
    "r_thigh2_study": 16490,
    "r_thigh3_study": 16564,
    "L_thigh1_study": 11253,
    "L_thigh2_study": 11327,
    "L_thigh3_study": 11378,
    # ── Shank clusters ──
    "r_sh1_study": 16923,
    "r_sh2_study": 17009,
    "r_sh3_study": 17089,
    "L_sh1_study": 11750,
    "L_sh2_study": 11840,
    "L_sh3_study": 11928,
}

# Ordered marker names (deterministic iteration order)
MHR_SURFACE_MARKER_NAMES: list[str] = list(MHR_SURFACE_MARKERS.keys())

# Vertex indices as array for fast numpy indexing
MHR_MARKER_INDICES: np.ndarray = np.array(
    list(MHR_SURFACE_MARKERS.values()), dtype=np.int64
)

# L/R pairs: (right_name, left_name) for symmetry enforcement
LR_PAIRS: list[tuple[str, str]] = [
    ("r.ASIS_study", "L.ASIS_study"),
    ("r.PSIS_study", "L.PSIS_study"),
    ("r_shoulder_study", "L_shoulder_study"),
    ("r_knee_study", "L_knee_study"),
    ("r_mknee_study", "L_mknee_study"),
    ("r_ankle_study", "L_ankle_study"),
    ("r_mankle_study", "L_mankle_study"),
    ("r_toe_study", "L_toe_study"),
    ("r_5meta_study", "L_5meta_study"),
    ("r_calc_study", "L_calc_study"),
    ("r_lelbow_study", "L_lelbow_study"),
    ("r_melbow_study", "L_melbow_study"),
    ("r_lwrist_study", "L_lwrist_study"),
    ("r_mwrist_study", "L_mwrist_study"),
    ("r_thigh1_study", "L_thigh1_study"),
    ("r_thigh2_study", "L_thigh2_study"),
    ("r_thigh3_study", "L_thigh3_study"),
    ("r_sh1_study", "L_sh1_study"),
    ("r_sh2_study", "L_sh2_study"),
    ("r_sh3_study", "L_sh3_study"),
]

# Midline markers (not mirrored)
MIDLINE_MARKERS: list[str] = ["C7_study"]

# Right-side markers to site manually (picker places these, auto-mirrors to left)
RIGHT_SIDE_MARKERS: list[str] = [r for r, _ in LR_PAIRS]


def compute_hjc_markers(
    vertices: np.ndarray,
    surface: dict[str, int] | None = None,
) -> dict[str, np.ndarray]:
    """Compute hip joint center markers via Bell's method (Bell et al. 1990).

    Args:
        vertices: MHR mesh vertices (V, 3) — single frame or rest pose.
            In MHR body-centric coords: X=right, Y=up, Z=backward.
        surface: Override surface marker dict. Defaults to MHR_SURFACE_MARKERS.

    Returns:
        Dict with RHJC_study and LHJC_study positions (3,).
    """
    if surface is None:
        surface = MHR_SURFACE_MARKERS

    def _get(name: str) -> np.ndarray:
        return vertices[surface[name]]

    rasi = _get("r.ASIS_study")
    lasi = _get("L.ASIS_study")
    rpsi = _get("r.PSIS_study")
    lpsi = _get("L.PSIS_study")
    asis_mid = (rasi + lasi) / 2
    psis_mid = (rpsi + lpsi) / 2
    pelvis_width = float(np.linalg.norm(rasi - lasi))

    # Pelvis coordinate system (ISB: X=fwd, Y=up, Z=right)
    z_axis = (rasi - lasi) / (pelvis_width + 1e-8)
    temp = asis_mid - psis_mid
    x_axis = temp / (np.linalg.norm(temp) + 1e-8)
    y_axis = np.cross(z_axis, x_axis)
    y_axis = y_axis / (np.linalg.norm(y_axis) + 1e-8)
    x_axis = np.cross(y_axis, z_axis)

    # Bell coefficients (fraction of pelvis width)
    result: dict[str, np.ndarray] = {}
    result["RHJC_study"] = asis_mid + pelvis_width * (
        -0.19 * x_axis - 0.30 * y_axis + 0.36 * z_axis
    )
    result["LHJC_study"] = asis_mid + pelvis_width * (
        -0.19 * x_axis - 0.30 * y_axis - 0.36 * z_axis
    )
    return result


def compute_hjc_markers_batch(
    surface_positions: np.ndarray,
    marker_names: list[str],
) -> tuple[np.ndarray, list[str]]:
    """Compute HJC markers for a batch of frames.

    Args:
        surface_positions: (N, 41, 3) per-frame surface marker positions.
        marker_names: list of 41 surface marker names (matching dim 1).

    Returns:
        (hjc_positions, hjc_names):
          hjc_positions: (N, 2, 3) per-frame HJC markers [RHJC, LHJC].
          hjc_names: ["RHJC_study", "LHJC_study"].
    """
    name_to_idx = {n: i for i, n in enumerate(marker_names)}

    def _get(name: str) -> np.ndarray:
        return surface_positions[:, name_to_idx[name]]  # (N, 3)

    rasi = _get("r.ASIS_study")
    lasi = _get("L.ASIS_study")
    rpsi = _get("r.PSIS_study")
    lpsi = _get("L.PSIS_study")
    asis_mid = (rasi + lasi) / 2
    psis_mid = (rpsi + lpsi) / 2
    pelvis_width = np.linalg.norm(rasi - lasi, axis=1, keepdims=True)  # (N, 1)

    z_axis = (rasi - lasi) / (pelvis_width + 1e-8)
    temp = asis_mid - psis_mid
    x_axis = temp / (np.linalg.norm(temp, axis=1, keepdims=True) + 1e-8)
    y_axis = np.cross(z_axis, x_axis)
    y_axis = y_axis / (np.linalg.norm(y_axis, axis=1, keepdims=True) + 1e-8)
    x_axis = np.cross(y_axis, z_axis)

    rhip = asis_mid + pelvis_width * (
        -0.19 * x_axis - 0.30 * y_axis + 0.36 * z_axis
    )
    lhip = asis_mid + pelvis_width * (
        -0.19 * x_axis - 0.30 * y_axis - 0.36 * z_axis
    )

    hjc_positions = np.stack([rhip, lhip], axis=1)  # (N, 2, 3)
    hjc_names = ["RHJC_study", "LHJC_study"]
    return hjc_positions, hjc_names


def extract_all_markers(
    vertices: np.ndarray,
    surface: dict[str, int] | None = None,
) -> dict[str, np.ndarray]:
    """Extract all 43 markers (41 surface + 2 HJC) from MHR mesh vertices.

    Args:
        vertices: MHR mesh vertices (V, 3) — single frame.
        surface: Override surface marker dict. Defaults to MHR_SURFACE_MARKERS.

    Returns:
        Dict of marker name → (3,) position (43 total).
    """
    if surface is None:
        surface = MHR_SURFACE_MARKERS

    result: dict[str, np.ndarray] = {}
    for name, vid in surface.items():
        result[name] = vertices[vid].copy()

    result.update(compute_hjc_markers(vertices, surface))
    return result
